name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
        if: ${{ steps.release.outputs.release_created }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
        if: ${{ steps.release.outputs.release_created }}
      - uses: rubygems/release-gem@v1
        if: ${{ steps.release.outputs.release_created }}
